/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Certificado__factory } from "./Certificado__factory";
export { Lock__factory } from "./Lock__factory";
