/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertificadoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autorizarCertificado"
      | "certificados"
      | "emitirCertificado"
      | "registrarUsuario"
      | "usuarios"
      | "verificarCertificado"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificadoAutorizado"
      | "CertificadoEmitido"
      | "UsuarioRegistrado"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autorizarCertificado",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificados",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitirCertificado",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registrarUsuario",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "usuarios",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificarCertificado",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "autorizarCertificado",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificados",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitirCertificado",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrarUsuario",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usuarios", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verificarCertificado",
    data: BytesLike
  ): Result;
}

export namespace CertificadoAutorizadoEvent {
  export type InputTuple = [id: BytesLike, instructor: AddressLike];
  export type OutputTuple = [id: string, instructor: string];
  export interface OutputObject {
    id: string;
    instructor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificadoEmitidoEvent {
  export type InputTuple = [
    id: BytesLike,
    estudiante: AddressLike,
    curso: string
  ];
  export type OutputTuple = [id: string, estudiante: string, curso: string];
  export interface OutputObject {
    id: string;
    estudiante: string;
    curso: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsuarioRegistradoEvent {
  export type InputTuple = [
    usuario: AddressLike,
    nombre: string,
    esInstructor: boolean
  ];
  export type OutputTuple = [
    usuario: string,
    nombre: string,
    esInstructor: boolean
  ];
  export interface OutputObject {
    usuario: string;
    nombre: string;
    esInstructor: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Certificado extends BaseContract {
  connect(runner?: ContractRunner | null): Certificado;
  waitForDeployment(): Promise<this>;

  interface: CertificadoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autorizarCertificado: TypedContractMethod<
    [id: BytesLike],
    [void],
    "nonpayable"
  >;

  certificados: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        estudiante: string;
        curso: string;
        fecha: string;
        hashContenido: string;
        autorizado: boolean;
      }
    ],
    "view"
  >;

  emitirCertificado: TypedContractMethod<
    [
      estudiante: AddressLike,
      curso: string,
      fecha: string,
      hashContenido: string
    ],
    [string],
    "nonpayable"
  >;

  registrarUsuario: TypedContractMethod<
    [nombre: string, esInstructor: boolean],
    [void],
    "nonpayable"
  >;

  usuarios: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, boolean] & {
        nombre: string;
        esInstructor: boolean;
        verificado: boolean;
      }
    ],
    "view"
  >;

  verificarCertificado: TypedContractMethod<
    [id: BytesLike],
    [
      [string, string, string, string, boolean] & {
        estudiante: string;
        curso: string;
        fecha: string;
        hashContenido: string;
        autorizado: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autorizarCertificado"
  ): TypedContractMethod<[id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificados"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        estudiante: string;
        curso: string;
        fecha: string;
        hashContenido: string;
        autorizado: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emitirCertificado"
  ): TypedContractMethod<
    [
      estudiante: AddressLike,
      curso: string,
      fecha: string,
      hashContenido: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrarUsuario"
  ): TypedContractMethod<
    [nombre: string, esInstructor: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usuarios"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, boolean] & {
        nombre: string;
        esInstructor: boolean;
        verificado: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verificarCertificado"
  ): TypedContractMethod<
    [id: BytesLike],
    [
      [string, string, string, string, boolean] & {
        estudiante: string;
        curso: string;
        fecha: string;
        hashContenido: string;
        autorizado: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CertificadoAutorizado"
  ): TypedContractEvent<
    CertificadoAutorizadoEvent.InputTuple,
    CertificadoAutorizadoEvent.OutputTuple,
    CertificadoAutorizadoEvent.OutputObject
  >;
  getEvent(
    key: "CertificadoEmitido"
  ): TypedContractEvent<
    CertificadoEmitidoEvent.InputTuple,
    CertificadoEmitidoEvent.OutputTuple,
    CertificadoEmitidoEvent.OutputObject
  >;
  getEvent(
    key: "UsuarioRegistrado"
  ): TypedContractEvent<
    UsuarioRegistradoEvent.InputTuple,
    UsuarioRegistradoEvent.OutputTuple,
    UsuarioRegistradoEvent.OutputObject
  >;

  filters: {
    "CertificadoAutorizado(bytes32,address)": TypedContractEvent<
      CertificadoAutorizadoEvent.InputTuple,
      CertificadoAutorizadoEvent.OutputTuple,
      CertificadoAutorizadoEvent.OutputObject
    >;
    CertificadoAutorizado: TypedContractEvent<
      CertificadoAutorizadoEvent.InputTuple,
      CertificadoAutorizadoEvent.OutputTuple,
      CertificadoAutorizadoEvent.OutputObject
    >;

    "CertificadoEmitido(bytes32,address,string)": TypedContractEvent<
      CertificadoEmitidoEvent.InputTuple,
      CertificadoEmitidoEvent.OutputTuple,
      CertificadoEmitidoEvent.OutputObject
    >;
    CertificadoEmitido: TypedContractEvent<
      CertificadoEmitidoEvent.InputTuple,
      CertificadoEmitidoEvent.OutputTuple,
      CertificadoEmitidoEvent.OutputObject
    >;

    "UsuarioRegistrado(address,string,bool)": TypedContractEvent<
      UsuarioRegistradoEvent.InputTuple,
      UsuarioRegistradoEvent.OutputTuple,
      UsuarioRegistradoEvent.OutputObject
    >;
    UsuarioRegistrado: TypedContractEvent<
      UsuarioRegistradoEvent.InputTuple,
      UsuarioRegistradoEvent.OutputTuple,
      UsuarioRegistradoEvent.OutputObject
    >;
  };
}
