/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Certificado } from "./Certificado";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Certificado__factory } from "./factories/Certificado__factory";
export { Lock__factory } from "./factories/Lock__factory";
